Workaround for IncompatibleClassChangeError(only occurred in Java9)
java.lang.IncompatibleClassChangeError: Method java.util.stream.Stream.of([Ljava/lang/Object;)Ljava/util/stream/Stream; must be InterfaceMethodref constant

(cherry picked from commit 2bd2407)