Update asciidoctor gradle plugin
Upgrading from 1.5.2. to 1.5.3 allows the asciidoctor tasks to
run successfully on jdk9, which failed with:

java.lang.RuntimeException: unsupported Java version: 9
    at org.jruby.RubyInstanceConfig.initGlobalJavaVersion(RubyInstanceConfig.java:1858)