Prior to beta 10 the shell would exit if an Error or Throwable was caught here, but this behavior made using Java 1.4 assertions in scripts difficult and could have other undesirable effects for other recoverable Errors such as NoClassDefFoundError. Truly non-recoverable Errors such as OOMEs will kill the JVM anyway, so no real need to exit or expect to catch such Errors here.
git-svn-id: http://svn.codehaus.org/groovy/trunk@1637 a5544e8c-8a19-0410-ba12-f9af4593a198