GROOVY-7105 Add try/catch for NoClassDefFoundError
SAM method resolution can cause loading of classes used in method
arguments (or as a return type).
When such a class is not present on a CLASSPATH, it causes a
NoClassDefFoundError even though the class may actually not be needed
for program execution.