Revert "GROOVY-8955: allow "def" as universal non-primitive return type"
https://github.com/apache/groovy/commit/23ea427dfff1623550e3f83c8b1a5f31ab944a8a#commitcomment-33849377

Paul King said:

I am wondering if this needs more work? If in the test I replace the `getMapping()` method with:
```
                    // "def" instead of explicit replacement for "T extends Property"
                    def getMappedForm() {
                        new Date()
                    }
```

I get a runtime exception:

```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'Fri Jun 07 19:49:19 AEST 2019' with class 'java.util.Date' to class 'Property'
```
Perhaps we should address that before making this commit?